### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Yedidyar** [SoftwareBrothers/adminjs#1029]
**Hi, I tried to start the adminJs library with sequelize and I got this error**

This is the stack trace 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')

navigation-element.tsx:29 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at NavigationElement (navigation-element.tsx:29:29)
    at renderWithHooks (global.bundle.js:38411:30)
    at mountIndeterminateComponent (global.bundle.js:41237:25)
    at beginWork (global.bundle.js:42475:28)
    at HTMLUnknownElement.callCallback (global.bundle.js:27374:26)
    at Object.invokeGuardedCallbackDev (global.bundle.js:27423:28)
    at invokeGuardedCallback (global.bundle.js:27485:43)
    at beginWork$1 (global.bundle.js:47379:19)
    at performUnitOfWork (global.bundle.js:46191:24)
    at workLoopSync (global.bundle.js:46122:17)


global.bundle.js:43511 The above error occurred in the <NavigationElement> component:

    at NavigationElement (http://localhost:8000/admin/frontend/assets/design-system.bundle.js:223282:6)
    at li
    at NavigationElementWrapper (http://localhost:8000/admin/frontend/assets/design-system.bundle.js:224603:6)
    at ul
    at section
    at I (http://localhost:8000/admin/frontend/assets/global.bundle.js:56166:17978)
    at Navigation (http://localhost:8000/admin/frontend/assets/design-system.bundle.js:224624:6)
    at SidebarResourceSectionOriginal (http://localhost:8000/admin/frontend/assets/app.bundle.js:3563:4)
    at WrapperComponent
    at section
    at I (http://localhost:8000/admin/frontend/assets/global.bundle.js:56166:17978)
    at section
    at I (http://localhost:8000/admin/frontend/assets/global.bundle.js:56166:17978)
    at SidebarOriginal (http://localhost:8000/admin/frontend/assets/app.bundle.js:3595:6)
    at WrapperComponent
    at section
    at I (http://localhost:8000/admin/frontend/assets/global.bundle.js:56166:17978)
    at App (http://localhost:8000/admin/frontend/assets/app.bundle.js:16269:52)
    at Router (http://localhost:8000/admin/frontend/assets/global.bundle.js:54202:42)
    at BrowserRouter (http://localhost:8000/admin/frontend/assets/global.bundle.js:55005:47)
    at styledComponents_browser_cjs.ThemeProvider (http://localhost:8000/admin/frontend/assets/global.bundle.js:56166:23387)
    at Provider (http://localhost:8000/admin/frontend/assets/global.bundle.js:50878:32)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.



global.bundle.js:46690 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at NavigationElement (navigation-element.tsx:29:29)
    at renderWithHooks (global.bundle.js:38411:30)
    at mountIndeterminateComponent (global.bundle.js:41237:25)
    at beginWork (global.bundle.js:42475:28)
    at HTMLUnknownElement.callCallback (global.bundle.js:27374:26)
    at Object.invokeGuardedCallbackDev (global.bundle.js:27423:28)
    at invokeGuardedCallback (global.bundle.js:27485:43)
    at beginWork$1 (global.bundle.js:47379:19)
    at performUnitOfWork (global.bundle.js:46191:24)
    at workLoopSync (global.bundle.js:46122:17)
```

**Installed libraries and their versions**

* adminjs": "^5.7.0"
* @adminjs/express": "^4.0.3"
* @adminjs/sequelize": "^2.1.1"

The database dialect is postgres

**Possible solution**
I don't sure, but it may be an edge case or Incorrect parsing.

From my investigation, it boils down to or the "useNavigationResources" hook or to the initialization of resources.
But its assumption...

**Screenshot of "resources" and the correspondence "useNavigationResources"**

![image](https://user-images.githubusercontent.com/42849252/155345959-9bbcf183-11af-403c-a1c2-e286767d990c.png)

P.S. your project is awesome 😀

**Comment by dziraf** [comment]
Are you using an `sqlite` db?

**Comment by Yedidyar** [comment]
Postgresql

**Comment by dziraf** [comment]
Can you try this solution? https://github.com/SoftwareBrothers/adminjs-sequelizejs/issues/54#issuecomment-734778960

This has previously been reported only in SQLite dbs

**Comment by Yedidyar** [comment]
Great it works😀

Is it mentioned in the documentation?
