### ISSUE TITLE
Bug with @adminjs/sequelize

### ISSUE THREAD

**Issue by Emilcul** [SoftwareBrothers/adminjs#1060]
I getting the error:
"There was an error fetching records, Check out console to see more information"

Also i noticed that the same stack has the same error in your example here:
https://admin-bro-example-app-staging.herokuapp.com/admin

If you tried to visit sequeizeResources tab you will see it, so it defenitly problem with the package

Installed libraries and their versions

    "@adminjs/express": "^4.1.0",
    "@adminjs/sequelize": "^2.1.5",
    "adminjs": "^5.7.4",

**Comment by dziraf** [comment]
The demo app uses an old version of both adminjs and @adminjs/sequelize. Can you tell what's displayed in your server's console?

**Comment by Emilcul** [comment]
```

**Comment by Emilcul** [comment]
Thats what I see in console. Don't understand where from "Products", i did't add this resource
```
Executing (default): SELECT "id", "name", "slug", "parentId", "imageUrl", "createdAt", "updatedAt", "categoryId" FROM "Categories" AS "Category" ORDER BY "Category"."name" ASC LIMIT 10 OFFSET 0;
Error: There are no resources with given id: "Products"
This is the list of all registered resources you can use:
Orders, Categories
    at AdminJS.findResource (/home/emilcul/work/store/node_modules/adminjs/lib/adminjs.js:253:13)
    at PropertyDecorator.reference (/home/emilcul/work/store/node_modules/adminjs/lib/backend/decorators/property/property-decorator.js:93:36)
    at /home/emilcul/work/store/node_modules/adminjs/lib/backend/utils/populator/populator.js:23:52
    at Array.filter (<anonymous>)
    at populator (/home/emilcul/work/store/node_modules/adminjs/lib/backend/utils/populator/populator.js:23:36)
    at Object.handler (/home/emilcul/work/store/node_modules/adminjs/lib/backend/actions/list/list-action.js:91:59)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ActionDecorator.handler (/home/emilcul/work/store/node_modules/adminjs/lib/backend/decorators/action/action-decorator.js:73:19)
    at async handler (/home/emilcul/work/store/node_modules/@adminjs/express/lib/buildRouter.js:33:30)
```

**Comment by dziraf** [comment]
do you have some kind of eager loading od products added in your Category sequelize model?

**Comment by Emilcul** [comment]
Yes, I have association with Product in Categories model, is it deprecated to have it?

**Comment by dziraf** [comment]
The association is fine, but if you automatically `include` it when you fetch `Categories`, they are loaded into `record.params` and treated as Category's fields. You would have to create a `before` hook which removes them from `params`/`request.payload`
