### ISSUE TITLE
Can't use filter to find from TypeORM resource

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1094]
**Describe the bug**
Filters don't work with TypeORM

**Installed libraries and their versions**

*   "@adminjs/express": "^4.1.0",
*    "@adminjs/typeorm": "^2.0.4",
*    "adminjs": "^5.9.8",
*    "typeorm": "^0.2.45",

**To Reproduce**
Create a custom action, in the handler try to use entity.find(new Filter())
```
              const user = context.record;
              const PatientDocuments =
                context._admin.findResource("PatientDocument");
              const filters = { fileName: "bc1f-1350342.jpeg" };
              const a = new Filter(filters, PatientDocuments);
              console.log(a.filters);
              const docs = await PatientDocuments.find(a, {});
```

**Expected behavior**
Return the rows that match the filter

**AdminJSOptions with schema**
```

@Entity("patient_documents")
export class PatientDocument extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  private id!: string;

  @Column()
  public fileName!: string;

  @ManyToOne(()=> Patient, patient => patient.documents)
  @JoinColumn({name: 'patient_id'})
  public patient_relation: Patient

  @RelationId((pDoc: PatientDocument) => pDoc.patient_relation)
  @Column()
  public patient_id!: number;
}
```

```

@Entity()
export class Patient extends BaseEntity {
...
  @OneToMany(() => PatientDocument, pDoc => pDoc.patient_relation)
  documents: PatientDocument[]
}
```
The filter object
```
{
  fileName: {
    path: 'fileName',
    property: Property {
      _path: 'fileName',
      _type: 'string',
      _isId: false,
      _isSortable: true,
      _position: 1,
      column: [ColumnMetadata],
      columnPosition: 1
    },
    value: 'bc1f-1350342.jpeg'
  }
}
```

The error

```
Error: undefined column was not found in the PatientDocument entity.
    at /home//WebstormProjects//src/find-options/FindOptionsUtils.ts:210:27
    at Array.forEach (<anonymous>)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (/home//WebstormProjects//src/find-options/FindOptionsUtils.ts:206:40)
    at Function.FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder (/home//WebstormProjects//src/find-options/FindOptionsUtils.ts:74:25)
    at EntityManager.<anonymous> (/home//WebstormProjects//src/entity-manager/EntityManager.ts:710:26)
    at step (/home//WebstormProjects//node_modules/tslib/tslib.js:143:27)
    at Object.next (/home//WebstormProjects//node_modules/tslib/tslib.js:124:57)
    at /home//WebstormProjects//node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home//WebstormProjects//node_modules/tslib/tslib.js:113:16)
```

Originally I was trying to filter on the foreign key ID, but just to test I used a random string. Neither way works

**Comment by dziraf** [comment]
Try to add sort info to the second param of find method. Also try to `await a.populate()`

**Comment by AshotN** [comment]
Didn't need `.populate()`

But the missing sort was the issue. Thank you for the help, I wasted hours reading the source code trying to figure it out. 
Can the typing please be fixed for these kinds of things!

```
const docs = await PatientDocuments.find(
                  a,
                  {sort: {sortBy: 'fileName'}}
                );
```
