### ISSUE TITLE
Derived DB values throw an error if used in reference

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1096]
**Describe the bug**
Values generated by ORM throw an error in AdminJS

**Installed libraries and their versions**
-     "@adminjs/express": "^4.1.0",
-     "@adminjs/typeorm": "^2.0.4",
-     "adminjs": "^5.9.8",
-     "typeorm": "^0.2.45",

Person entity
```
  @Column()
  public firstName!: string;

  @Column()
  public lastName!: string;

  protected fullName: string;

  @OneToMany(() => PersonDocument, (pDoc) => pDoc.person_relation)
  documents: PersonDocument[];
```
Document entity
```

  @ManyToOne(() => Person, (p) => p.documents)
  @JoinColumn({ name: "person_id" })
  public person_relation: Person;

  @RelationId((pDoc: PersonDocument) => pDoc.person_relation)
  @Column()
  public person_id!: number;
```

Person resource
```
{
        resource: Person,
        options: {
          properties: {
            fullName: {
              isTitle: true,
            },
          },
...


The error is only thrown if visiting the resource page of Person Documents. 
The error is

```
Error: fullName column was not found in the Person entity.
    at /home//WebstormProjects//src/find-options/FindOptionsUtils.ts:210:27
    at Array.forEach (<anonymous>)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (/home//WebstormProjects//src/find-options/FindOptionsUtils.ts:206:40)
    at Function.FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder (/home//WebstormProjects//src/find-options/FindOptionsUtils.ts:74:25)
    at EntityManager.<anonymous> (/home//WebstormProjects//src/entity-manager/EntityManager.ts:710:26)
    at step (/home//WebstormProjects//node_modules/tslib/tslib.js:143:27)
    at Object.next (/home//WebstormProjects//node_modules/tslib/tslib.js:124:57)
    at /home//WebstormProjects//node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home//WebstormProjects//node_modules/tslib/tslib.js:113:16)

```

But everything works anyway, the error just floods the console

**Comment by dziraf** [comment]
this should work fine if `fullName` is a getter

**Comment by AshotN** [comment]
Something like this?

```
  @Column({readonly: true})
  protected fullName: string;

  @AfterLoad()
  getFullName() {
    this.fullName = this.firstName + " " + this.lastName;
  }
```

Or is there a way to avoid having fullName be a column?

**Comment by AshotN** [comment]
I see what you are saying, I haven't had a chance to test it yet. But it makes sense, so I'll close the issue. Thanks for your help.
