### ISSUE TITLE
Refused to execute script from '{baseUrl}/admin/frontend/assets/components.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by jcliftonlee** [SoftwareBrothers/adminjs#1105]
**Describe the bug**
I've noticed that after adding authentication, I'm seeing a bug in the console:

"Refused to execute script from '{baseUrl}/admin/frontend/assets/components.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

I also see:
```
app.bundle.js:15193 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at RecordsTable (frontend/assets/app.bundle.js:15193:17)
    at renderWithHooks (frontend/assets/global.bundle.js:38142:30)
    at updateFunctionComponent (frontend/assets/global.bundle.js:40373:32)
    at beginWork (frontend/assets/global.bundle.js:41949:28)
    at HTMLUnknownElement.callCallback (frontend/assets/global.bundle.js:23533:26)
    at Object.invokeGuardedCallbackDev (frontend/assets/global.bundle.js:23582:28)
    at invokeGuardedCallback (frontend/assets/global.bundle.js:23637:43)
    at beginWork$1 (frontend/assets/global.bundle.js:46542:19)
    at performUnitOfWork (frontend/assets/global.bundle.js:45496:24)
    at workLoopSync (frontend/assets/global.bundle.js:45469:34)

global.bundle.js:42866 The above error occurred in the <RecordsTable> component:
    in RecordsTable (created by List)
    in section (created by styled.section)
    in styled.section (created by List)
    in List (created by BaseActionComponent)
    in ErrorBoundary$1 (created by BaseActionComponent)
    in BaseActionComponent (created by ResourceAction)
    in section (created by styled.section)
    in styled.section (created by ResourceAction)
    in ResourceAction (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in section (created by styled.section)
    in styled.section (created by App)
    in section (created by styled.section)
    in styled.section (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Unknown
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary$1.
```

It's possible the issue with the bundle is a red herring, but I suspect a component from that bundle is unable to be imported.

**Installed libraries and their versions**

```
  "@adminjs/express": "^4.1.0",
  "@adminjs/nestjs": "^4.0.1",
  "@adminjs/typeorm": "^2.0.3",
  "adminjs": "^5.8.1",
  "express-formidable": "^1.2.0",
  "express-session": "^1.17.2",
```

**To Reproduce**
1. Log in
2. Go to a resource page
3. Get logged out
5. See error

**Expected behavior**
Expect to be able to log in and view resource

**Screenshots**

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**
 - OS: macOS
 - Browser: Chrome
 - Version: 100

**Smartphone (please complete the following information if relevant):**

**Additional context**

**Comment by dziraf** [comment]
Is your `components.bundle.js` being generated?

**Comment by jcliftonlee** [comment]
How are these files typically generated in production?
