### ISSUE TITLE
TypeORM connector + documentation seems to be broken

### ISSUE THREAD

**Issue by maximelebastard** [SoftwareBrothers/adminjs#1121]
**Describe the bug**

With a fresh install of latest versions of AdminJS and TypeORM, it seems there is no way to properly add Resources without breaking AdminJS.

**Installed libraries and their versions**

* adminjs@5.10.0
* @adminjs/express@4.1.0
* @adminjs/typeorm@3.0.0
* typeorm@0.3.6
* pg@8.7.13

**To Reproduce**
1. Install typeorm, @adminjs/express, @adminjs/typeorm
2. Follow the documentation, but realize that createConnection is deprecated and that Model.getRepository is not documented by TypeORM
3. Use that index.ts code

```json
{
  "dependencies": {
    "@adminjs/express": "^4.1.0",
    "@adminjs/typeorm": "^3.0.0",
    "@types/express": "^4.17.13",
    "@types/swagger-ui-express": "^4.1.3",
    "adminjs": "^5.10.0",
    "body-parser": "^1.20.0",
    "concurrently": "^7.1.0",
    "cors": "^2.8.5",
    "express": "^4.18.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.2",
    "nodemon": "^2.0.16",
    "pg": "^8.7.3",
    "swagger-ui-express": "^4.3.0",
    "ts-node": "^10.7.0",
    "tsc": "^2.0.4",
    "tsoa": "^4.0.0",
    "typeorm": "^0.3.6",
    "typescript": "^4.6.4"
  }
}

```

```typescript
import "reflect-metadata";
import { BaseEntity, Column, DataSource, Entity, PrimaryGeneratedColumn } from "typeorm";
import express, { Request, Response } from "express";
import bodyParser from "body-parser";
import swaggerUi from "swagger-ui-express";
import AdminJS from "adminjs";
import AdminJSExpress from "@adminjs/express";
import * as TypeOrmAdapter from "@adminjs/typeorm";

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  email: string;

  @Column()
  name: string;

  @Column()
  status?: "Happy" | "Sad" = "Happy";

  @Column("varchar", { array: true })
  phoneNumbers: string[];
}

export const PostgresDatasource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "example",
  database: "password",
  entities: [User],
  synchronize: true,
})
PostgresDatasource.initialize();

const app = express();

AdminJS.registerAdapter(TypeOrmAdapter);
const adminJs = new AdminJS({
  databases: [PostgresDatasource],
  resources: [{ resource: User, options: { parent: { name: "foobar" } } }],
  rootPath: "/admin",
});
const router = AdminJSExpress.buildRouter(adminJs);
app.use(adminJs.options.rootPath, router);

app.listen(3000, () => console.log("Server live on port 3000"));
```

**Expected behavior**
AdminJS to load properly my resources

**Actual behavior**
```
NoResourceAdapterError: There are no adapters supporting one of the resource you provided
[0]     at /workspace/api/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:99:15
```

**Additional informations**
If I dig in, I can see that `/resources-factory.js:99:15` is actually calling `adapter.Resource.isAdapterFor(resourceObject)` where adapter is the @adminjs/typeorm one.

On node_modules/@adminjs/typeorm/lib/Resource.js:211, to check if the resource can be loaded - AdminJS calls `rawResource.getRepository().metadata` in a try catch that silents any error.
If I remove the try/catch, I get that following error

```
Error: DataSource is not set for this entity.
at Function.getRepository (/workspace/api/src/repository/BaseEntity.ts:115:19)
```

BaseEntity.ts:115 is doing the following:
```typescript
    static getRepository() {
        const dataSource = this.dataSource;
        if (!dataSource)
            throw new Error(`DataSource is not set for this entity.`);
        return dataSource.getRepository(this);
    }
```

I can fix that issue by calling useDataSource on each of my entities (not ideal, but...)

```typescript
// ...
export const PostgresDatasource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "example",
  database: "example",
  entities: [User],
  synchronize: true,
})
PostgresDatasource.initialize();

User.useDataSource(PostgresDatasource);

const app = express();
// ...
```

But even doing that, I get another error - this time about Metadata

```
[0] /workspace/api/src/data-source/DataSource.ts:422
[0]         if (!metadata) throw new EntityMetadataNotFoundError(target)
```

I'd like to play it by the documentation, but it seems outdated as createConnection is deprecated by TypeORM.
My feeling is that AdminJS tries to load the entities before TypeORM actually ends his initialization work.

**Comment by maximelebastard** [comment]
Datasource initialization is async. Sorry for bothering. This works

```
import "reflect-metadata";
import {
  BaseEntity,
  Column,
  DataSource,
  Entity,
  PrimaryGeneratedColumn,
} from "typeorm";
import express, { Request, Response } from "express";
import bodyParser from "body-parser";
import swaggerUi from "swagger-ui-express";
import AdminJS from "adminjs";
import AdminJSExpress from "@adminjs/express";
import * as TypeOrmAdapter from "@adminjs/typeorm";

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  email: string;

  @Column()
  name: string;

  @Column()
  status?: "Happy" | "Sad" = "Happy";

  @Column("varchar", { array: true })
  phoneNumbers: string[];
}

export const PostgresDatasource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "example",
  database: "example",
  entities: [User],
  synchronize: true,
});
PostgresDatasource.initialize().then(() => {
  console.log({ m: User.getRepository().metadata });

  const app = express();

  AdminJS.registerAdapter(TypeOrmAdapter);
  const adminJs = new AdminJS({
    databases: [PostgresDatasource],
    resources: [{ resource: User, options: { parent: { name: "foobar" } } }],
    rootPath: "/admin",
  });
  const router = AdminJSExpress.buildRouter(adminJs);
  app.use(adminJs.options.rootPath, router);

  app.use(
    bodyParser.urlencoded({
      extended: true,
    })
  );
  app.use(bodyParser.json());

  app.use("/docs", swaggerUi.serve, async (_req: Request, res: Response) => {
    return res.send(
      swaggerUi.generateHTML(await import("../build/swagger.json"))
    );
  });

  app.listen(3000, () => console.log("Server live on port 3000"));
});

```
