### ISSUE TITLE
use hapi demo error

### ISSUE THREAD

**Issue by tank537285** [SoftwareBrothers/adminjs#1162]
I try to start with hapi
```
const AdminJSPlugin = require('@adminjs/hapi')
const Hapi = require('@hapi/hapi')

const adminJsOptions = {}
const server = Hapi.server({ port: process.env.PORT || 8080 })
const start = async () => {
    await server.register({
        plugin: AdminJSPlugin,
        options: adminJsOptions,
    })

    await server.start()
}

start()
```
package.json
```
{
  "name": "nodeadmintest",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./app"
  },
  "dependencies": {
    "@adminjs/express": "^4.1.3",
    "@adminjs/hapi": "^5.0.2",
    "@adminjs/sequelize": "^2.1.5",
    "@hapi/boom": "^10.0.0",
    "@hapi/cookie": "^11.0.2",
    "@hapi/hapi": "^20.2.2",
    "@hapi/inert": "^6.0.5",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "express": "^4.18.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "http-errors": "~1.6.2",
    "jade": "~1.11.0",
    "morgan": "~1.9.0",
    "sequelize": "^6.21.1"
  }
}

```

output error
```
/usr/local/bin/node /Users/admin/Desktop/git/nodejs/nodeadmintest/app.js
/Users/admin/Desktop/git/nodejs/nodeadmintest/node_modules/@hapi/hapi/lib/server.js:456
                const name = item.plugin.name || item.plugin.pkg.name;
                                         ^

TypeError: Cannot read properties of undefined (reading 'name')
    at internals.Server.register (/Users/admin/Desktop/git/nodejs/nodeadmintest/node_modules/@hapi/hapi/lib/server.js:456:42)
    at start (/Users/admin/Desktop/git/nodejs/nodeadmintest/app.js:7:18)
    at Object.<anonymous> (/Users/admin/Desktop/git/nodejs/nodeadmintest/app.js:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.4.0
```

**Comment by dziraf** [comment]
Please try to update Hapi plugin to 6.0.2; I'll reopen if it doesn't work.
