### ISSUE TITLE
Getting style errors when passing auth object

### ISSUE THREAD

**Issue by lxbbkn** [SoftwareBrothers/adminjs#1180]
Getting style errors when passing auth object, it works well without it.

**error**
```console
C:\Users\User\Desktop\backend\node_modules\@adminjs\design-system\build\atoms\box\box.js:47
  line-height: ${({ theme }) => theme.lineHeights.default};
                                                  ^
TypeError: Cannot read properties of undefined (reading 'default')
    at chunk (C:\Users\User\Desktop\backend\node_modules\@adminjs\design-system\build\atoms\box\box.js:47:51)
    at flatten (C:\Users\User\Desktop\backend\node_modules\styled-components\src\utils\flatten.js:68:22)
    at e.generateAndInjectStyles (C:\Users\User\Desktop\backend\node_modules\styled-components\src\models\ComponentStyle.js:91:29)
    at useInjectedStyle (C:\Users\User\Desktop\backend\node_modules\styled-components\src\models\StyledComponent.js:87:22)
    at propsForElement (C:\Users\User\Desktop\backend\node_modules\styled-components\src\models\StyledComponent.js:125:30)
    at I (C:\Users\User\Desktop\backend\node_modules\styled-components\src\models\StyledComponent.js:174:44)
    at renderWithHooks (C:\Users\User\Desktop\backend\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5662:16)
    at renderForwardRef (C:\Users\User\Desktop\backend\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5846:18)
    at renderElement (C:\Users\User\Desktop\backend\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6009:11)
    at renderNodeDestructiveImpl (C:\Users\User\Desktop\backend\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
```

**dependencies**
```json
{
  "@adminjs/express": "^5.0.0",
  "@adminjs/mongoose": "^3.0.0",
  "@adminjs/nestjs": "^5.0.0",
  "@nestjs/common": "^9.0.4",
  "@nestjs/core": "^9.0.4",
  "@nestjs/mongoose": "^9.2.0",
  "@nestjs/platform-express": "^9.0.4",
  "adminjs": "^6.0.1",
  "express": "^4.18.1",
  "express-formidable": "^1.2.0",
  "express-session": "^1.17.3",
  "mongodb": "^4.8.0",
  "mongoose": "^6.4.5",
}
```

**app.module**
```javascript
AdminJS.registerAdapter(AdminJSMongoose)

@Module({
  imports: [
    MongooseModule.forRoot('mongodb://localhost:27017/nest'),
    AdminModule.createAdminAsync({
      imports: [SchemasModule],
      inject: [getModelToken('Admin')],
      useFactory: (...resources) => ({
        adminJsOptions: {
          rootPath: '/admin',
          resources,
        },
        // It will work if we remove this
        auth: {
          authenticate: async (email, password) => null,
          cookieName: 'name',
          cookiePassword: 'password',
        },
        sessionOptions: {
          secret: 'secret',
          resave: false,
          saveUninitialized: true,
        },
      }),
    }),
    SchemasModule,
  ],
})
export class AppModule {}
```

**schemas.module**
```javascript
@Module({
  imports: [
    MongooseModule.forFeature([{ name: 'Admin', schema: AdminSchema }]),
  ],
  exports: [MongooseModule],
})
export class SchemasModule {}
```

**Comment by matbjo-dev** [comment]
I am also getting the same error. " yarn add react@^18.1.0 react-dom@^18.1.0 styled-components@^5.3.5" this fixed it. Thanks.
