### ISSUE TITLE
TypeError: this.model.findOneBy is not a function

### ISSUE THREAD

**Issue by adminha** [SoftwareBrothers/adminjs#1219]
I've installed & successfully initialized AdminJS, thank you! It looks great!
Everything works fine, except one thing, when I click on a record of one of the entities, it throws an error and says:
`[Nest] 9416  - 08/22/2022, 1:08:57 PM   ERROR [ExceptionsHandler] this.model.findOneBy is not a function
TypeError: this.model.findOneBy is not a function
    at Resource.<anonymous> (C:\Users\...\node_modules\@adminjs\typeorm\src\Resource.ts:81:39)
    at Generator.next (<anonymous>)
    at C:\Users\...\node_modules\@adminjs\typeorm\lib\Resource.js:8:71    
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\...\node_modules\@adminjs\typeorm\lib\Resource.js:4:12)
    at Resource.findOne (C:\Users\...\node_modules\@adminjs\typeorm\lib\Resource.js:75:16)
    at ApiController.recordAction (C:\Users\...\node_modules\adminjs\lib\backend\controllers\api-controller.js:160:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handler (C:\Users\...\node_modules\@adminjs\express\src\buildRouter.ts:46:22)`

I don't know where's the problem, I just followed everything you've said in the documentation, the panel showed up without any issues, I even saw the DB records inside admin dashboard, I even added a new record for one of my entities, everything works fine except viewing a single record of an entity.
P.S: I don't know if it can cause or not, I created an abstract class which extends BaseEntity, then I extended my entities from this abstract class.

**Comment by dziraf** [comment]
Extending `BaseEntity` is a requirement for typeorm adapter to work.

Can you share the version of your `@adminjs/typeorm` and `typeorm`?

`@adminjs/typeorm` version `>=3.0.0` only supports `typeorm` version `^0.3.x` which has breaking changes.

**Comment by dziraf** [comment]
Closing because no response from original poster
