### ISSUE TITLE
You must provide selection conditions in order to find a single row.

### ISSUE THREAD

**Issue by KHJcode** [SoftwareBrothers/adminjs#1272]
**Describe the bug**

```
Error: You must provide selection conditions in order to find a single row.
    at EntityManager.findOne (/node_modules/typeorm/entity-manager/EntityManager.js:540:19)
    at Repository.findOne (/node_modules/typeorm/repository/Repository.js:209:29)
    at Function.findOne (/node_modules/typeorm/repository/BaseEntity.js:244:37)
    at Resource.<anonymous> (/node_modules/@admin-bro/typeorm/lib/Resource.js:65:47)
    at Generator.next (<anonymous>)
    at /node_modules/@admin-bro/typeorm/lib/Resource.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/@admin-bro/typeorm/lib/Resource.js:4:12)
    at Resource.findOne (/node_modules/@admin-bro/typeorm/lib/Resource.js:64:16)
    at ApiController.recordAction (/node_modules/admin-bro/lib/backend/controllers/api-controller.js:160:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handler (/node_modules/@admin-bro/express/lib/buildRouter.js:32:30)
```

<br/>

`findOne(id)` signature was dropped in [Typeorm 0.3.0](https://github.com/typeorm/typeorm/releases/0.3.0).

But AdminJS is still using [this code](https://github.com/SoftwareBrothers/adminjs/blob/master/src/backend/controllers/api-controller.ts#L159).
Do you have any plans to suggest solutions to this, except for the version downgrade?

<br/>

**Installed libraries and their versions**

* adminjs@4.0.1
* typeorm@0.3.0

<br/>

**Additional context**
I have a plan to pull request for this issue.

**Comment by dziraf** [comment]
You are using outdated packages.
`@admin-bro/typeorm` is now `@adminjs/typeorm`
`@admin-bro/express` is now `@adminjs/express`
`admin-bro` is now `adminjs`

**Comment by KHJcode** [comment]
> You are using outdated packages. `@admin-bro/typeorm` is now `@adminjs/typeorm` `@admin-bro/express` is now `@adminjs/express` `admin-bro` is now `adminjs`

Does that mean that the current admin.js code supports it?

**Comment by dziraf** [comment]
`adminjs` is ORM agnostic, the code you linked uses underlying ORM adapter which in your case is `@admin-bro/typeorm`. `@adminjs/typeorm` has been supporting typeorm 0.3.x+ for months now.

**Comment by KHJcode** [comment]
Thank you for your quick response.
