### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by Boredude** [SoftwareBrothers/adminjs#1312]
Getting ```TypeError: Cannot read properties of undefined (reading 'default')``` when running 

```TypeError: Cannot read properties of undefined (reading 'default')
    at chunk (/Users/omribitan/Workspace/platera/node_modules/@adminjs/design-system/build/atoms/box/box.js:47:51)
    at flatten (/Users/omribitan/Workspace/platera/node_modules/styled-components/src/utils/flatten.js:68:22)
    at e.generateAndInjectStyles (/Users/omribitan/Workspace/platera/node_modules/styled-components/src/models/ComponentStyle.js:91:29)
    at useInjectedStyle (/Users/omribitan/Workspace/platera/node_modules/styled-components/src/models/StyledComponent.js:87:22)
    at propsForElement (/Users/omribitan/Workspace/platera/node_modules/styled-components/src/models/StyledComponent.js:125:30)
    at I (/Users/omribitan/Workspace/platera/node_modules/styled-components/src/models/StyledComponent.js:174:44)
    at renderWithHooks (/Users/omribitan/Workspace/platera/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
    at renderForwardRef (/Users/omribitan/Workspace/platera/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5846:18)
    at renderElement (/Users/omribitan/Workspace/platera/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6009:11)
    at renderNodeDestructiveImpl (/Users/omribitan/Workspace/platera/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
[ERROR] 10:40:09 TypeError: Cannot read properties of undefined (reading 'default')

**Installed libraries and their versions**

* adminjs@6.0.1
* @adminjs/express@5.0.1
* @adminjs/mongoose@3.0.0

**Comment by Boredude** [comment]
Fixed it by upgrading adminjs to 6.6.5
