### ISSUE TITLE
Fixes a security vulnerability in rollup-plugin-terser

### ISSUE THREAD

**Issue by faroukbouzouita** [SoftwareBrothers/adminjs#1343]
High            Terser insecure use of regular expressions before v4.8.1 and  
                  v5.14.2 leads to ReDoS                                        

  Package         terser                                                        

  Patched in      >=4.8.1                                                       
  Dependency of   admin-bro

  Path            admin-bro > rollup-plugin-terser > terser

  More info       https://github.com/advisories/GHSA-4wf5-vphf-c2xc

**Comment by faroukbouzouita** [comment]
@dziraf  
I migrated from admin bro to adminjs(last version)
I changed the config but when i start application i have this error:
(node:21508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'useState' of
null
at Object.useState (D:\projets\equipe\back\Equipty-Admin\node_modules\react\cjs\react.development.js:1622:21)
at ae (D:\projets\equipe\back\Equipty-Admin\node_modules\styled-components\src\models\StyleSheetManager.js:34:33)
