### ISSUE TITLE
Enhancement: Unhandled type: Map

### ISSUE THREAD

**Issue by trevex** [SoftwareBrothers/adminjs#144]
Recently array support was implemented: https://github.com/SoftwareBrothers/admin-bro/issues/90

However currently [Maps](https://mongoosejs.com/docs/schematypes.html#maps) are not supported yet. 

Apart from this feature request is there a way to work around this issue, e.g. representation as string (via its JSON form)?

**Comment by wojtek-krysiak** [comment]
can you write the example schema - maybe I will be able to help from there.

**Comment by LucasLeandro1204** [comment]
@wojtek-krysiak 

```js
import Mongoose, { Schema } from 'mongoose';

const {
  Map,
  String,
  Boolean,
  ObjectId,
} = Schema.Types;

const schema = new Schema({
  config: Map,

  url: String,

  component: {
    type: String,
  },
}),
```

**Comment by salvacnj** [comment]
Hello, is this feature implemented?

I'm trying to use it but not working for me


`  @Prop({ type: Map })
  @ApiProperty({
    example: { "1605689439": 30.32, "1605689445": 20.35 }
  })
  samples: Map<string, number>;

  @Prop(raw({
    firstName: { type: String },
    lastName: { type: String }
  }))
  details: Record<string, any>;`
  
  
  
![imagen](https://user-images.githubusercontent.com/36660968/119152793-eb22ab80-ba50-11eb-80b7-cb02038f6a69.png)
![imagen](https://user-images.githubusercontent.com/36660968/119152875-fece1200-ba50-11eb-9ff1-3f2b008b3714.png)

**Comment by marciondg** [comment]
I have the same issue, any workaround?
![image](https://user-images.githubusercontent.com/53331055/157491384-90625bda-ff71-4ffb-aa8e-c1c9e275a1e5.png)
![image](https://user-images.githubusercontent.com/53331055/157491394-4a1bc7e6-8c8c-417b-be82-27337a819180.png)
![image](https://user-images.githubusercontent.com/53331055/157491415-bb48f485-efed-428d-a373-a8b826ca4426.png)
![image](https://user-images.githubusercontent.com/53331055/157491427-78271cc3-9677-46f3-a7d1-17608f399226.png)

**Comment by krzysztofstudniarek** [comment]
Currently we don't have plans to implement such type. It would be very hard considering current data model in AdminJS.

**Comment by Bilits** [comment]
Hi @trevex @krzysztofstudniarek just wanted to check since its been around 2 years since the last update on this thread, is adminjs now supports mongoose maps? below is my schema structure: 

import mongoose, { Schema } from "mongoose";

const scenarioSchema = new Schema({
  scenario: { type: String },
  status: { type: String },
  minPlayer: { type: Number },
  maxPlayer: { type: Number },
  imagePath: { type: String },
  wideImagePath: { type: String },
  articlePath: { type: String },
  youtubePath: { type: String },
  aparatPath: { type: String },
  isCustom: { type: Boolean, default: false },
  abilities: {
    type: Map,
    of: [
      {
        ability: {
          type: Schema.Types.ObjectId,
          ref: "Ability",
        },
        count: {
          type: Number,
          required: true,
          min: 1,
          default: 1,
        },
      },
    ],
  },
});

export default mongoose.model("scenario", scenarioSchema);


and everytime i try to open this in adminJs i am getting the following error:

2024-03-07T01:12:50.935Z error: Error Handler Middleware - Error: {"method":"GET","path":"/admin/api/resources/scenario/actions/list","errorMessage":"There are no resources with given id: \"Ability\"\nThis is the list of all registered resources you can use:\nuser, ability, room, scenario, malicious","stack":"Error: There are no resources with given id: \"Ability\"\nThis is the list of all registered resources you can use:\nuser, ability, room, scenario, malicious\n    at AdminJS.findResource (file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/adminjs.js:183:13)\n    at PropertyDecorator.reference (file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/backend/decorators/property/property-decorator.js:77:36)\n    at file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/backend/utils/populator/populator.js:14:52\n    at Array.filter (<anonymous>)\n    at populator (file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/backend/utils/populator/populator.js:14:36)\n    at Object.handler (file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/backend/actions/list/list-action.js:71:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ActionDecorator.handler (file:///Users/moe/Desktop/gorgine-backend/node_modules/adminjs/lib/backend/decorators/action/action-decorator.js:56:19)\n    at async file:///Users/moe/Desktop/gorgine-backend/node_modules/@adminjs/express/lib/buildRouter.js:24:22"}

**Comment by codeit13** [comment]
Is Map implemented yet?

It's been almost 2.5 years, How do @adminJS team expect someone to use this in production.

To be honest, I love the admin JS, dashborad, but these kind of bugs just keeps arriving time to time in adminJS, Can't really use this in production setup now.

**Comment by Bilits** [comment]
@codeit13 Its very frustrating for us too - we are already in production and cant use 2 collection at all because of this issue
