### ISSUE TITLE
[Bug]: Can't import package

### ISSUE THREAD

**Issue by Neil-Brown** [SoftwareBrothers/adminjs#1479]
### What happened?

I have installed the following packages `@adminjs/express: ^6.0.0`, `@adminjs/mongoose: 4.0.0,` and `adminjs: ^7.0.0`. In my `app.js` file I am importing them as per the docs as follows:

```
import AdminJS from 'adminjs'
import * as AdminJSExpress from '@adminjs/express'
```
But when I run the app I get the following error:

```
file:///C:/Users/USER01/github/express-template/node_modules/adminjs/lib/locale/index.js:1
import deLocale from './de/translation.json' assert { type: 'json' };
                                             ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

My node version is `v14.17.3`

### Bug prevalence

Whenever I run the app

### AdminJS dependencies version

```
"dependencies": {
    "@adminjs/express": "^6.0.0",
    "@adminjs/mongoose": "^4.0.0",
    "adminjs": "^7.0.0",
    "compression": "^1.7.4",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "helmet": "^6.1.5",
    "pug": "^3.0.2",
    "serve-favicon": "^2.5.0",
    "tslib": "^2.5.0"
  }
```

### What browsers do you see the problem on?

Chrome

### Relevant log output

```bash
file:///C:/Users/USER01/github/express-template/node_modules/adminjs/lib/locale/index.js:1
import deLocale from './de/translation.json' assert { type: 'json' };
                                             ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

### Relevant code that's giving you issues

```TypeScript
import AdminJS from 'adminjs'
import * as AdminJSExpress from '@adminjs/express'
```
```

**Comment by dziraf** [comment]
Please update NodeJS to LTS (v18)

**Comment by andersonszdc** [comment]
the error continue, same installing the nodeJS v18

**Comment by rccoding** [comment]
getting this error please help

**Comment by nachomglz** [comment]
I stopped getting this error using node v20

**Comment by shubhampr07** [comment]
i am still getting this error in node 20 as well

**Comment by RSFelix** [comment]
In my case it never worked normally, neither with node 18 nor with 20. The only solution that worked for me was to replace **import** with **require**, like this:

`import { createRequire } from 'module';
const require = createRequire(import.meta.url);

const deLocale = require('./de/translation.json');
const enLocale = require('./en/translation.json');
const esLocale = require('./es/translation.json');
const itLocale = require('./it/translation.json');
const jaLocale = require('./ja/translation.json');
const plLocale = require('./pl/translation.json');
const ptBrLocale = require('./pt-BR/translation.json');
const uaLocale = require('./ua/translation.json');
const zhCNLocale = require('./zh-CN/translation.json');

export * from './config.js';
export * from './default-config.js';
export const locales = {
  de: deLocale,
  en: enLocale,
  es: esLocale,
  it: itLocale,
  ja: jaLocale,
  pl: plLocale,
  'pt-BR': ptBrLocale,
  ua: uaLocale,
  'zh-CN': zhCNLocale
};`

using Node 20

**Comment by IbraheemHaseeb7** [comment]
I was getting issue using Node 20. I updated to Node 20.18.2 and it works now. It shows some warnings on JSON. You can update your Node version to 22 to use it safely without any issues.

**Comment by bmbaron** [comment]
Still having this issue and using Node v.23.4.0
