### ISSUE TITLE
[Bug]: actionContext.action in bulkAction of ApiClient is an empty value.

### ISSUE THREAD

**Issue by steel-hyuk** [SoftwareBrothers/adminjs#1492]
### Contact Details

hi@u-hoo.com

### What happened?

I am trying to access the selected data by customizing bulkAction.
However, bulkAction function in ApiClient is not getting the data exported from handler.

### Bug prevalence

It happens every moment I try to do that action.

### AdminJS dependencies version

"adminjs": "^7.0.0",
"@adminjs/express": "^6.0.0",
"@adminjs/nestjs": "^6.0.1",
"@adminjs/typeorm": "^5.0.0",

### What browsers do you see the problem on?

Chrome

### Relevant log output

```bash
[Nest] 79945  - 2023. 05. 04. 오후 6:25:30   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'handler')
TypeError: Cannot read properties of undefined (reading 'handler')
    at ApiController.bulkAction (file:///Users/eunhyuk/works/admin/octopus-admin/node_modules/adminjs/lib/backend/controllers/api-controller.js:192:55)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/eunhyuk/works/admin/octopus-admin/node_modules/@adminjs/express/lib/buildRouter.js:24:22
```

### Relevant code that's giving you issues

```TypeScript
customComponent.tsx

const {
        data: { exportedData },
      } = await new ApiClient().bulkAction({
        resourceId: resource.id,
        actionName: 'excelExport',
        params: {
          type
        },
      });
```

feature.ts
```
export const excelExportHandler = async (request, response, context) => {
  const { records, resource, h } = context;
  const parser = Parsers[request.query?.type ?? 'json'].export;
  const parsedData = parser(records);

  return {
    records: records.map((record) => record.toJSON(context.currentAdmin)),
    exportedData: parsedData,
    redirectUrl: h.resourceUrl({ resourceId: resource._decorated?.id() || resource.id() })
  };
}
```

exportHandler.ts
```
      excel: {
        name: 'excelExport',
        handler: bulkActionHandler(excelExportHandler),
        component: excelExportComponent,
        icon: 'File',
        showInDrawer: true,
        actionType: 'bulk'
      }
```
```

**Comment by dziraf** [comment]
What's `bulkActionHandler`?

**Comment by steel-hyuk** [comment]
> What's `bulkActionHandler`?

```
      excel: {
        name: 'excelExport',
        handler: excelExportHandler,
        component: excelExportComponent,
        icon: 'File',
        showInDrawer: true,
        actionType: 'bulk'
      }
```

I tried to write a function that returns the handler, but it is the same as the code above

**Comment by dziraf** [comment]
can you try to remove:
```
        name: 'excelExport',
```
from your configuration and just use `excel` as action name?
