### ISSUE TITLE
NoResourceAdapterError when using TypeORM

### ISSUE THREAD

**Issue by exp131** [SoftwareBrothers/adminjs#1554]
I have the same error.
```TypeScript
import AdminJS from 'adminjs';
import AdminJSExpress from '@adminjs/express';
import 'reflect-metadata';
import * as AdminJSTypeORM from '@adminjs/typeorm';
import express, { Express } from 'express';
import dotenv from 'dotenv';


// Database connection
import dataSource from './orm/datasource.js';
import { User } from './orm/models/user.js';

dotenv.config();


const port = process.env.PORT || 3000;

const start = async () => {
  const app: Express = express();
  await dataSource.initialize();

  // Initializtion
  AdminJS.registerAdapter({
    Resource: AdminJSTypeORM.Resource,
    Database: AdminJSTypeORM.Database
  });

  const adminOptions = {
    resources: [ User ]
  }
  const admin = new AdminJS(adminOptions);
  const adminRouter = AdminJSExpress.buildRouter(admin);
  app.use(admin.options.rootPath, adminRouter);


  app.listen(port, () => {
    console.log(`AdminJS started on http://localhost:${port}${admin.options.rootPath}`)
  });

}

start();
```

And the error: 
```
[0] 5:55:44 PM - Found 0 errors. Watching for file changes.
[1] (node:31804) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[1] (node:31804) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[1] file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:73
[1]         throw new NoResourceAdapterError(resourceObject);
[1]               ^
[1] 
[1] NoResourceAdapterError: There are no adapters supporting one of the resource you provided
[1]     at file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:73:15
[1]     at Array.map (<anonymous>)
[1]     at ResourcesFactory._convertResources (file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:68:22)
[1]     at ResourcesFactory.buildResources (file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:28:35)
[1]     at new AdminJS (file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/node_modules/adminjs/lib/adminjs.js:80:39)
[1]     at start (file:///Users/vitalyradchik/Devel/StilyoApps/Tests/adminjs-app-ts/dist/main.js:23:19) {
[1]   resource: [class User extends BaseEntity]
[1] }
[1] 
[1] Node.js v20.0.0
```

_Originally posted by @exp131 in https://github.com/SoftwareBrothers/adminjs/issues/976#issuecomment-1705411603_

**Comment by dziraf** [comment]
```
import dataSource from './orm/datasource.js';
import { User } from './orm/models/user.js';

dotenv.config();
```

Can you check if you have access to environment variables in your datasource/User files? `dotenv` should rather be at the top of the file. I prefer to use a CLI version myself:
```
    "start": "dotenv -c '.env' -- node dist/server/index.js",
```

**Comment by exp131** [comment]
Yes, it is available. I even disabled dotenv completely in the project, but the error remains the same.

**Comment by exp131** [comment]
To update:
Here data source and entity configs used:

`orm/datasource.ts`
```typescript
import { DataSource } from 'typeorm';

const SqliteDataSource = new DataSource({
  type: 'sqlite',
  database: './db.sqlite'
});

export default SqliteDataSource;
```


`orm/models/user.ts`
```typescript
import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'User' })
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  public firstName: string;

  @Column()
  public lastName: string;
}
```

**Comment by exp131** [comment]
I just followed the docs, but this is a solution. Now it working fine, thanks a lot @dziraf

**Comment by exp131** [comment]
Issue fixeed

**Comment by ParasRai2** [comment]
Incase of TypeORM, just extending the entity fixed the issue

import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from "typeorm";

@Entity()
export class User extends BaseEntity {
....
}
