### ISSUE TITLE
[Bug]: TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by elosoman** [SoftwareBrothers/adminjs#1717]
### What happened?

I've just bootstrapped an install of AdminJS using Express and Prisma to connect to a MySql db. My resources are displayed in the UI but when selected they error. From the network console in the browser ...

http://localhost:3000/admin/api/resources/ValidationRule/actions/search which results in a 500 and this error 

TypeError: Do not know how to serialize a BigInt

In fact the ValidationRule table has an ID defined as  

model ValidationRule {
  validationRuleId    BigInt                @id @default(autoincrement())
}

I believe I ran over a previously closed issue which suggested changing BigInt to Int, but that is not reasonable for this solution. Thoughts.

Thank you

### Bug prevalence

Whenever I access a resource which has a BigInt as an ID field.

### AdminJS dependencies version

  "dependencies": {
    "@adminjs/express": "^6.1.0",
    "@adminjs/prisma": "^5.0.1",
    "@prisma/client": "^5.6.0",
    "adminjs": "^7.7.2",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "mysql2": "latest"
  },

### Relevant log output

```bash
AdminJS available at http://localhost:3000/admin
✔ Finish bundling: 1 files
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at stringify (/Users/benjamin/repos/promoToolAdminJS/promotooladminjs/node_modules/express/lib/response.js:1160:12)
    at ServerResponse.json (/Users/benjamin/repos/promoToolAdminJS/promotooladminjs/node_modules/express/lib/response.js:271:14)
    at ServerResponse.send (/Users/benjamin/repos/promoToolAdminJS/promotooladminjs/node_modules/express/lib/response.js:162:21)
    at file:///Users/benjamin/repos/promoToolAdminJS/promotooladminjs/node_modules/@adminjs/express/lib/buildRouter.js:32:17
```

### Relevant code that's giving you issues

```TypeScript
still searching the code base.
```

**Comment by elosoman** [comment]
I was able workaround this by defining a serializer

```
declare global {
  interface BigInt {
    toJSON: () => string;
  }
}

BigInt.prototype.toJSON = function (): string {
  return this.toString();
};
```
