### ISSUE TITLE
Using mongoose-unique-validator plugin breaks assets updates

### ISSUE THREAD

**Issue by domingosl** [SoftwareBrothers/adminjs#585]
When using the [mongoose-unique-validator plugin](https://www.npmjs.com/package/mongoose-unique-validator) you can create a delete assets from AdminBro UI. But when trying to modify one you get an error as follows:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at createValidationError (/Users/domingosarmiento/WebstormProjects/sp-api-v1/node_modules/@admin-bro/mongoose/src/utils/create-validation-error.js:4:25)
    at Resource.update (/Users/domingosarmiento/WebstormProjects/sp-api-v1/node_modules/@admin-bro/mongoose/src/resource.js:179:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Installed libraries and their versions**

* admin-bro@2.0.1
* admin-bro-expressjs@2.0.0
* admin-bro-mongoose@1.4.0
* mongoose-unique-validator: "^2.0.3"
* mongoose: "^5.9.25"

**To Reproduce**
Just add a mongoose resource to AdminBro that uses the plugin, create a new asset and then try to edit it.

This is how my model is defined:
```
const mongoose = require('mongoose');
const timestamps = require('mongoose-timestamp');
const uniqueValidator = require('mongoose-unique-validator');


const shopCategorySchema = new mongoose.Schema({

    name: {
        type: String,
        unique: true,
        required: true
    }

}, { collection: 'shopCategories' });

shopCategorySchema.plugin(timestamps);
shopCategorySchema.plugin(uniqueValidator);

module.exports = exports = mongoose.model('shopCategory', shopCategorySchema);
```

And this is how my AdminBro is initialized:
```
module.exports.init = async (app, db) => {

    AdminBro.registerAdapter(AdminBroMongoose);

    const adminBro = new AdminBro({
        //databases: [db],
        rootPath: '/',
        resources: [
            { resource: require('../app/models/shop-categories'), options: { editProperties: ['name'], parent: storeParentOptions } }
        ],
        branding: {
            companyName: 'ScuolaPay admin',
            softwareBrothers: false
        },
        locale: locale
    });

    const router = AdminBroExpress.buildRouter(adminBro);
    app.use(adminBro.options.rootPath, router);


    app.listen(process.env.ADMIN_PANEL_PORT, async () => {

        api.logger.info('Admin UI running!', { port: process.env.ADMIN_PANEL_PORT, tagLabel });

    });

}
```

**Comment by wojtek-krysiak** [comment]
added this to the current milestone. And we will take a look at
