### ISSUE TITLE
search action `before` query filters not working

### ISSUE THREAD

**Issue by sajjad-fatehi** [SoftwareBrothers/adminjs#840]
hi.
i have a problem that is for role-based records cant filter users own data 
for example in docs we use somthing like this :

> `list:{
>             before: async (request, context) => {
>               const { currentAdmin } = context
>               return {
>                 ...request,
>                 query: {
>                   ...request.query,
>                   'filters.service': currentAdmin.service
>                 }
>               }
>             }
>  }`

and it works . but ! in search action filters not working ... after i checked admin-bro source i found search-action.ts and saw its diffrent
if uses 

> `const queryString = request.params && request.params.query`

i tried to use somthing like this but i got error :

> `
> search:{
>             before: async (request, context) => {
>               const { currentAdmin } = context
>               return {
>                 ...request,
>                 params:{
>                   ...request.params,
>                   query: {
>                     ...request.params.query,
>                     'filters.public_id': currentAdmin.service
>                   }
>                 }
>               }
>             }
>           }
> `

this is the error :

> `
> TypeError: Cannot read property 'type' of null
>     at F:\E\Nodejs\PJ\server\node_modules\@admin-bro\mongoose\lib\src\utils\convert-filter.js:21:26
>     at Array.reduce (<anonymous>)
>     at Filter.reduce (F:\E\Nodejs\PJ\server\node_modules\admin-bro\lib\backend\utils\filter\filter.js:99:40)
>     at Object.exports.convertFilter (F:\E\Nodejs\PJ\server\node_modules\@admin-bro\mongoose\lib\src\utils\convert-filter.js:19:19)
>     at Resource.find (F:\E\Nodejs\PJ\server\node_modules\@admin-bro\mongoose\lib\src\resource.js:61:36)
>     at Object.handler (F:\E\Nodejs\PJ\server\node_modules\admin-bro\lib\backend\actions\search\search-action.js:51:36)
>     at ActionDecorator.invokeHandler (F:\E\Nodejs\PJ\server\node_modules\admin-bro\lib\backend\decorators\action\action-decorator.js:117:26)
>     at ActionDecorator.handler (F:\E\Nodejs\PJ\server\node_modules\admin-bro\lib\backend\decorators\action\action-decorator.js:73:30)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async handler (F:\E\Nodejs\PJ\server\node_modules\@admin-bro\express\lib\buildRouter.js:32:30)
> `

so i loged some data and found that in search-action.js filters is somthing like this :
`name.service`
it take the title of resource 

> `titleProperty()`

so what you suggest for filter resources in search
**i cant ignore it because all users can see each other data in new or edit**

**Comment by sajjad-fatehi** [comment]
can you add somthing like this to search-action.ts : 

> import * as flat from 'flat'
> 
>     const { query } = request
>     const { subFilters = {} } = flat.unflatten(query || {})
> 
>     const queryStringFilters = queryString ? { [titlePropertyName]: queryString } : {}
>     const filters = { ...queryStringFilters, ...subFilters }
