### ISSUE TITLE
Cannot read property 'handler' of undefined in costum action record

### ISSUE THREAD

**Issue by rahou0** [SoftwareBrothers/adminjs#915]
im trying to create costum action record but when i click on it i receive this error :

TypeError: Cannot read property 'handler' of undefined
    at ApiController.recordAction (C:\Users\rahim\Documents\vereatablesubdomain\node_modules\adminjs\lib\backend\controllers\api-controller.js:167:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handler (C:\Users\rahim\Documents\vereatablesubdomain\node_modules\@adminjs\express\lib\buildRouter.js:32:30)

my costum action record:
```
actions: {
   accept: {
          icon: "Add",
          name: "Accept",
          actionType: "record",
          component: false,
          handler: async (request, response, context) => {
            const { record, resource, currentAdmin, translateMessage } = context;
            return {
              notice: {
                message: translateMessage("successfullyUpdated", resource.id()),
                type: "success",
              },
              record: record.toJSON(currentAdmin),
            };
          },
        },
}
```
**Installed libraries and their versions**

  "@admin-bro/sequelize": "^1.3.0-beta.5",
    "@adminjs/express": "^4.0.0",
    "@adminjs/sequelize": "^2.0.0",
    "adminjs": "^5.2.1",

**Comment by rahou0** [comment]
this error occured because im using accept and Accept in name
i resolved this by using same name in both (accept or Accept).
