### ISSUE TITLE
Body Parser error when i click login admin panel

### ISSUE THREAD

**Issue by kadirsheik45** [SoftwareBrothers/adminjs#916]
**Describe the bug**
Error: You probably used old `body-parser` middleware, which is not compatible
with admin-bro-expressjs. In order to make it work you will have to
1. move body-parser invocation after the admin bro setup like this:
const adminBro = new AdminBro()
const router = new buildRouter(adminBro)
app.use(adminBro.options.rootPath, router)
// body parser goes after the AdminBro router
app.use(bodyParser())
2. Upgrade body-parser to the latest version and use it like this:
app.use(bodyParser.json())
    at E:\Program files\node.js\fogob\node_modules\admin-bro-expressjs\plugin.js:157:12
    at Layer.handle [as handle_request] (E:\Program files\node.js\fogob\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:317:13)
    at E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\Program files\node.js\fogob\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:317:13)
    at E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (E:\Program files\node.js\fogob\node_modules\body-parser\lib\types\json.js:101:7)
    at Layer.handle [as handle_request] (E:\Program files\node.js\fogob\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Program files\node.js\fogob\node_modules\express\lib\router\index.js:317:13)

**Installed libraries and their versions**

 "admin-bro": "^4.0.1",
    "admin-bro-expressjs": "^2.1.1",
    "admin-bro-mongoose": "^0.5.2",
    "argon2": "^0.28.2",
    "aws-sdk": "^2.958.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.2",
    "jsonwebtoken": "^8.5.1",
    "mongodb": "^4.0.1",
    "mongoose": "^5.13.4",
    "multer": "^1.4.1"

**To Reproduce**

just try to login 

**Expected behavior**
crash the app after trying to log in and output the above errror

**Comment by dziraf** [comment]
Please add more details, did you try to do what the error says?
