### ISSUE TITLE
can not use custom component

### ISSUE THREAD

**Issue by btshj** [SoftwareBrothers/adminjs#933]
**Describe the bug**

````javascript

  const adminJs = new AdminJS({
    databases: [mongooseDb],
    rootPath,
    dashboard: {
      handler: async () => {},
      component: AdminJS.bundle('../components/dashboard'),
    },
    ...adminJsOptions,
  });

````

````javascript
import React from 'react';
// import { Box } from '@adminjs/design-system';

const Dashboard = () => {
  return <div> Hello </div>;
};

export default Dashboard;

````

error info :

````shell
[0] Error: 'default' is not exported by build/components/dashboard.jsx, imported by .adminjs/.entry.js
[0]     at error (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:151:30)
[0]     at Module.error (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:10059:16)
[0]     at Module.traceVariable (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:10444:29)
[0]     at ModuleScope.findVariable (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:9227:39)
[0]     at Identifier.bind (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:4591:40)
[0]     at AssignmentExpression.bind (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:2886:23)
[0]     at ExpressionStatement.bind (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:2886:23)
[0]     at Program.bind (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:2882:31)
[0]     at Module.bindReferences (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:10055:18)
[0]     at Graph.sortModules (/Users/going101/snail/project/out/cloud-mgt/node_modules/rollup/dist/shared/rollup.js:20447:20)

````

**Installed libraries and their versions**

* adminjs@5.2.1
* @adminjs/express@4.0.0
* @adminjs/mongoose@2.0.0
* @adminjs/design-system@2.0.2

**Comment by dziraf** [comment]
Can you show the contents of your `build/components/dashboard.jsx`?

**Comment by sebsn86** [comment]
Hi,

It's worked for me with this configuration :

`dashboard: {
        handler: async () => {
            return {...}
        },
        component: AdminBro.bundle(join(__dirname, '/path/to/dashboard.component.jsx'))
    },`

and the dashboard.component.jsx :

`const Dashboard = () => {
    const [data, setData] = useState({some: 'test'});

    return (
        <Box variant="grey">
            <Box variant="white">
                some: {data.some}
            </Box>
        </Box>);
};

export default Dashboard;`
