### ISSUE TITLE
cant connect to mongo

### ISSUE THREAD

**Issue by shar27** [SoftwareBrothers/adminjs#948]
Hey, 

I am fairly new to this. I followed this - https://www.section.io/engineering-education/nodejs-adminbro/. 

However, I am still having issues. I keep getting this error. 

  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\Owner\adminbro\node_modules\mongoose\lib\connection.js:797:32)
    at C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:332:10
    at C:\Users\Owner\adminbro\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Owner\adminbro\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:1153:10)
    at Mongoose.connect (C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:331:20)
    at Object.<anonymous> (C:\Users\Owner\adminbro\config\db.config.js:5:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 337660229,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
            at connectionFailureError (C:\Users\Owner\adminbro\node_modules\mongodb\lib\cmap\connect.js:293:20)
            at Socket.<anonymous> (C:\Users\Owner\adminbro\node_modules\mongodb\lib\cmap\connect.js:267:22)
            at Object.onceWrapper (node:events:510:26)
            at Socket.emit (node:events:390:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}

This is my server.js file 

const express = require('express');
const app = express();
const AdminBro = require('admin-bro');
const AdminBroMongoose = require('@admin-bro/mongoose')
const expressAdminBro = require('@admin-bro/express');

app.get('/', ()=>response.send('Hello World'));

// Database
const connection = require('./config/db.config');

connection.once('open', ()=>console.log('Database connected Successfully'));
//connection.on('error',()=>console.log('Error', err));

//Admin Bro and Models
const Customer = require('./models/Customer')
const Admin = require('./models/Admin')

AdminBro.registerAdapter(AdminBroMongoose)
const AdminBroOptions = {
  resources: [Admin, Customer],
}

const adminBro = new AdminBro(AdminBroOptions)
const router = expressAdminBro.buildRouter(adminBro)

app.use(adminBro.options.rootPath, router)

app.listen(8000, ()=>console.log('Listening at Port 8000'));

what is  wrong?

**Comment by dziraf** [comment]
The way I see it your database connection either:
1. Cannot be established, for example the DB url is invalid
2. Connection isn't awaited so Admin panel starts before you connect to your database
Try to wrap your code in an async function i. e.:

```
const express = require('express');
const AdminBro = require('admin-bro');
const AdminBroMongoose = require('@admin-bro/mongoose')
const expressAdminBro = require('@admin-bro/express');

const connection = require('./config/db.config');
const Customer = require('./models/Customer');
const Admin = require('./models/Admin');

AdminBro.registerAdapter(AdminBroMongoose);

const run = async () => {
  await connection(); // or await connection;
  const app = express();
  app.get('/', ()=>response.send('Hello World'));

  const adminBroOptions = {
    resources: [Admin, Customer],
  };

  const adminBro = new AdminBro(adminBroOptions);
  const router = expressAdminBro.buildRouter(adminBro);

  app.use(adminBro.options.rootPath, router);

  app.listen(8000, ()=>console.log('Listening at Port 8000'));
}

run();
```

We also rebranded to `adminjs` a couple of months ago so you might want to install `adminjs` and `@adminjs/<module>` packages instead

**Comment by shar27** [comment]
updated everthing to adminjs and wrapped it like you mentioned. 

New error - await connection(); // or await connection;
TypeError: connection is not a function
    at run (C:\Users\Owner\adminbro\server.js:13:9)
    at Object.<anonymous> (C:\Users\Owner\adminbro\server.js:31:1)

The code - 

const express = require('express');
const AdminJS = require('adminjs');
const AdminJSMongoose = require('@adminjs/mongoose')
const AdminJSExpress = require('@adminjs/express');

const connection = require('./config/db.config');
const Customer = require('./models/Customer');
const Admin = require('./models/Admin');

AdminJS.registerAdapter(AdminJSMongoose);

const run = async () => {
  await connection(); // or await connection;
  const app = express();
  app.get('/', ()=>response.send('Hello World'));

  const adminJsOptions = {
    resources: [Admin, Customer],
  };

  const adminJs = new AdminJS(adminJsOptions);
  
  const router = AdminJSExpress.buildRouter(adminJs)


  app.use(adminJs.options.rootPath, router);

  app.listen(8000, ()=>console.log('Listening at Port 8000'));
}

run();
](url)

**Comment by dziraf** [comment]
change that to `await connection` then, that's why I left the comment

**Comment by shar27** [comment]
the previous issue came back -

  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\Owner\adminbro\node_modules\mongoose\lib\connection.js:797:32)
    at C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:332:10
    at C:\Users\Owner\adminbro\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Owner\adminbro\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:1153:10)
    at Mongoose.connect (C:\Users\Owner\adminbro\node_modules\mongoose\lib\index.js:331:20)
    at Object.<anonymous> (C:\Users\Owner\adminbro\config\db.config.js:5:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 351374069,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
            at connectionFailureError (C:\Users\Owner\adminbro\node_modules\mongodb\lib\cmap\connect.js:293:20)
            at Socket.<anonymous> (C:\Users\Owner\adminbro\node_modules\mongodb\lib\cmap\connect.js:267:22)
            at Object.onceWrapper (node:events:510:26)
            at Socket.emit (node:events:390:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}

**Comment by shar27** [comment]
this is the db.config.js 

const mongoose = require('mongoose')

const DB_URI = 'mongodb://localhost:27017/AdminJs';
//Database connection
mongoose.connect(DB_URI,
{useNewUrlParser: true, useUnifiedTopology: true});

const connection = mongoose.connection

module.exports = connection

**Comment by dziraf** [comment]
just remove the db config file and add this:

```
const DB_URI = 'mongodb:localhost:27017/AdminBro';

await mongoose.connect(DB_URI,
{useNewUrlParser: true, useUnifiedTopology: true});
```
instead of `await connection`

**Comment by shar27** [comment]
like this ---

const express = require('express');
const AdminJS = require('adminjs');
const AdminJSMongoose = require('@adminjs/mongoose')
const AdminJSExpress = require('@adminjs/express');

const connection = require('./config/db.config');
const Customer = require('./models/Customer');
const Admin = require('./models/Admin');

AdminJS.registerAdapter(AdminJSMongoose);

const DB_URI = 'mongodb:localhost:27017/AdminBro';

await mongoose.connect(DB_URI,
{useNewUrlParser: true, useUnifiedTopology: true});
  const adminJs = new AdminJS(adminJsOptions);
  
  const router = AdminJSExpress.buildRouter(adminJs)


  app.use(adminJs.options.rootPath, router);

  app.listen(8000, ()=>console.log('Listening at Port 8000'));


gave a new error -

await mongoose.connect(DB_URI,
^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by shar27** [comment]
const express = require('express');
const AdminJS = require('adminjs');
const AdminJSMongoose = require('@adminjs/mongoose')
const AdminJSExpress = require('@adminjs/express');


const Customer = require('./models/Customer');
const Admin = require('./models/Admin');

AdminJS.registerAdapter(AdminJSMongoose);

const DB_URI = 'mongodb:localhost:27017/AdminJS';

await mongoose.connect(DB_URI,
{useNewUrlParser: true, useUnifiedTopology: true});
  const adminJs = new AdminJS(adminJsOptions);
  
  const router = AdminJSExpress.buildRouter(adminJs)


  app.use(adminJs.options.rootPath, router);

  app.listen(8000, ()=>console.log('Listening at Port 8000'));

**Comment by dziraf** [comment]
you have to import mongoose

**Comment by dziraf** [comment]
Closing because of lack of response
