### ISSUE TITLE
Failed to update user entity

### ISSUE THREAD

**Issue by dominik992** [SoftwareBrothers/adminjs#953]
I get an error when trying to update my User entity.
```
query: START TRANSACTION
query: UPDATE "user" SET "password" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" IN ($1) RETURNING "updated_at" -- PARAMETERS: [38,"$2b$10$z7bMv0oPYWOUvdd2p3tMtOSmF2V4ivNULV2OlsTLLvuElY4kyCzRu"]
query: UPDATE "home" SET "user_id" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["111",38]
query: UPDATE "home" SET "user_id" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: [111,null]
query failed: UPDATE "home" SET "user_id" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: [111,null]
error: error: null value in column "user_id" violates not-null constraint
    at Parser.parseErrorMessage (/Users/dominikdragicevic/projects/good_house_backend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/dominikdragicevic/projects/good_house_backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/dominikdragicevic/projects/good_house_backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/dominikdragicevic/projects/good_house_backend/node_modules/pg-protocol/dist/index.js:10:42)

```

User has OneToMany relation to homes:
```
  @OneToMany(() => Home, (home) => home.user, {
    eager: true,
    onDelete: 'CASCADE',
  })
  homes: Home[];
```

And Home has ManyToOne relation to users
```
  @ManyToOne(() => User, (user) => user.homes, { nullable: false })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column('int', { nullable: false })
  user_id: number;

```

    "@adminjs/design-system": "^2.0.1",
    "@adminjs/express": "^4.0.0",
    "@adminjs/nestjs": "^2.0.0",
    "@adminjs/passwords": "^2.0.0",
    "@adminjs/typeorm": "^2.0.0",
    "@adminjs/upload": "^2.0.0",

Any ideas?

**Comment by dziraf** [comment]
Are you sure it's adminjs issue? Your SQL queries are passing `null` to `user_id` which means `null` is actually passed to `user_id`.

**Comment by dominik992** [comment]
I didn't write that query. It's just a log I got from typorm after clicking update in adminjs dashboard

**Comment by dziraf** [comment]
Do you have any extra hooks for your update action? The generated SQL doesn't fail when updating `user` but `home`

**Comment by dziraf** [comment]
Closing because of lack of response
